// export * from "./delete-application";
// export * from "./delete-user";
// export * from "./get-applications";
// export * from "./get-auth";
export * from "./get-vakken";
export * from "./get-klassen";
export * from "./get-niveaus";
export * from "./get-doelgroepen";
// export * from "./post-application";
// export * from "./post-login";
// export * from "./post-preauth";
export * from "./post-file";
export * from "./post-vak";
export * from "./post-klas";
export * from "./post-niveau";
export * from "./post-doelgroep";
// export * from "./put-user";
